.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-REMOVE\-SQUASHED\-COMMITS" "1" "May 2019" "" ""
.
.SH "NAME"
\fBgit\-remove\-squashed\-commits\fR \- A bash helper to remove squashed commits\. Useful when you start new feature branch not from master but from another branch\.
.
.SH "SYNOPSIS"
git\-remove\-squashed\-commits [\.\.\.]
.
.P
\fB\.\.\.\fR \- are the commands that passed to \fBgit commit\fR
.
.SH "DESCRIPTION"
When your project uses a merge method \fBSquash and merge\fR for Pull Requests, your commits will be squashed into a single one commit\. That\'s cool but it may take a while before your PR is merged\. While that, you may want to create another branch, using your not\-yet\-merged branch (instead of master)\. So you end up that these commits come to your new branch and it would be cool if you are able to remove them once your previous PR is merged\. This git helper solves the problem \- so you have a cleaner PR without these commits from another PR\.
.
.P
This command removes the commits that were being squashed\.
.
.SH "COPYRIGHT"
(c) 2019 Jerry Green
.
.P
Bats is released under the terms of an MIT\-style license\.
